### ISSUE TITLE
Copying over defs doesn't ensure unique ids

### ISSUE THREAD

**Issue by jacobp100** [Hiswe/gulp-svg-symbols#50] opened 2018-01-31 13:42 UTC
If I have two files that define something like `<defs><clipPath id="path0_fill" ... /></defs>`, the id `path0_fill` will be defined twice, breaking one of the images.

This happens with pretty much any SVG export from figma.

**Comment by Hiswe** [comment] 2018-02-01 04:48
@jacobp100 Indeed. I keep this plugin as dumb as possible :) 

For doing this stuff I think I would use  [gulp-cheerio](https://www.npmjs.com/package/gulp-cheerio)

```js
return gulp
.src(`source/*.svg`)
.pipe(cheerio({
  run: ($, file) => {
    const $def = $(`def`);
    if (!$def.length) return;
    const $defsNodesWithIds = $def.find(`[id]`)
    if (!$defsNodesWithIds.length) return;
    const idsList = $defsNodesWithIds.map( (i, el) => $(el).attr(`id`) )
    // change the id to be unic per file
    const newIds  = idsList.map( id => `${file.path.replace('/', '-')}_id` )
    // To be done: replacing the reference to the old ids by the new
    // ...
  },
  parserOptions: {
    xmlMode: true,
  },
}))
```
This is of course a very basic way of doing it. 
It can be optimized by making a dictionary of `defs` that  prevent duplicated content for example.

On a side note every vector editor has his own way of producing SVG and most of the time SVG optimization are very specific to one software output. So beginning to mess with the SVG may produce undesirable files.  I prefer developers to have the full control of it, so the result is more predictable.

Hope it helps!

**Comment by Hiswe** [comment] 2018-02-08 05:27
Closing because it's not a bug.

And you can also use [gulp-svgmin](https://github.com/ben-eb/gulp-svgmin) beforehand.

**Comment by jacobp100** [comment] 2018-02-08 07:40
I think this is more of a spec compliance issue than tailoring to software outputs. How would you handle mask elements?

**Comment by Hiswe** [comment] 2018-02-08 08:13
@jacobp100 Can you send me two test files? It will be easier for me to understand what you're trying to achieve

**Comment by jacobp100** [comment] 2018-02-08 08:58
An example of things that need will ids de-duplicated is https://www.figma.com/file/TTuGu6jSxAJ2a7Mg3i02BwF5/Untitled. It has masks and linear gradients, both of which require ids in SVG.

The exports are:

```svg
<svg width="48" height="48" viewBox="0 0 48 48" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
<title>2</title>
<desc>Created using Figma</desc>
<g id="Canvas" transform="translate(-3 24)">
<g id="2">
<mask id="mask0_alpha" mask-type="alpha">
<g id="Group">
<g id="Rectangle">
<use xlink:href="#path0_fill" transform="translate(11 -13)" fill="#C4C4C4"/>
</g>
<g id="Rectangle">
<use xlink:href="#path0_fill" transform="translate(11 1)" fill="#C4C4C4"/>
</g>
</g>
</mask>
<g id="Rectangle 2" mask="url(#mask0_alpha)">
<use xlink:href="#path1_fill" transform="translate(3 -24)" fill="url(#paint2_linear)"/>
</g>
</g>
</g>
<defs>
<linearGradient id="paint2_linear" x1="0" y1="0" x2="1" y2="0" gradientUnits="userSpaceOnUse" gradientTransform="matrix(2.93915e-15 48 -48 2.93915e-15 48 -2.93915e-15)">
<stop offset="0" stop-color="#F2994A"/>
<stop offset="1" stop-color="#F2C94C"/>
</linearGradient>
<path id="path0_fill" d="M 0 6C 0 2.68629 2.68629 0 6 0L 26 0C 29.3137 0 32 2.68629 32 6L 32 6C 32 9.31371 29.3137 12 26 12L 6 12C 2.68629 12 0 9.31371 0 6L 0 6Z"/>
<path id="path1_fill" d="M 0 0L 48 0L 48 48L 0 48L 0 0Z"/>
</defs>
</svg>
```

and

```svg
<svg width="48" height="48" viewBox="0 0 48 48" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
<title>3</title>
<desc>Created using Figma</desc>
<g id="Canvas" transform="translate(-51 24)">
<g id="3">
<mask id="mask0_alpha" mask-type="alpha">
<g id="Group">
<g id="Rectangle">
<use xlink:href="#path0_fill" transform="translate(59 8)" fill="#C4C4C4"/>
</g>
<g id="Rectangle">
<use xlink:href="#path0_fill" transform="translate(59 -20)" fill="#C4C4C4"/>
</g>
<g id="Rectangle">
<use xlink:href="#path0_fill" transform="translate(59 -6)" fill="#C4C4C4"/>
</g>
</g>
</mask>
<g id="Rectangle 2" mask="url(#mask0_alpha)">
<use xlink:href="#path1_fill" transform="translate(51 -24)" fill="url(#paint3_linear)"/>
</g>
</g>
</g>
<defs>
<linearGradient id="paint3_linear" x1="0" y1="0" x2="1" y2="0" gradientUnits="userSpaceOnUse" gradientTransform="matrix(2.93915e-15 48 -48 2.93915e-15 48 -2.93915e-15)">
<stop offset="0" stop-color="#F2994A"/>
<stop offset="1" stop-color="#F2C94C"/>
</linearGradient>
<path id="path0_fill" d="M 0 6C 0 2.68629 2.68629 0 6 0L 26 0C 29.3137 0 32 2.68629 32 6L 32 6C 32 9.31371 29.3137 12 26 12L 6 12C 2.68629 12 0 9.31371 0 6L 0 6Z"/>
<path id="path1_fill" d="M 0 0L 48 0L 48 48L 0 48L 0 0Z"/>
</defs>
</svg>
```

**Comment by Hiswe** [comment] 2018-02-08 11:09
@jacobp100 I've came up with an additional example here:

https://github.com/Hiswe/gulp-svg-symbols/blob/master/examples/gulpfile.js#L85-L112

so after following the [example instructions](https://github.com/Hiswe/gulp-svg-symbols#more-examples) you can `npm run svg-containing-identical-id`

There was a minor issue in the demo page (corrected in 3.0.2) but:

- the generated demo-page doesn't work properly in Firefox (Ok in Chrome & Safari)
- It was impossible for me to open the Figma's SVG in other editors 
  - Illustrator CS6 just rasterize the file
  - Affinity Designer render me a square gradient
  - Sketch App seems to render the thing almost like Firefox

So… I don't know. Looks like this Figma's output is very strange for some softwares.
Is there any export option in Figma?

**Comment by Hiswe** [comment] 2018-02-08 13:18
@jacobp100 update on the example file

https://github.com/Hiswe/gulp-svg-symbols/blob/master/examples/gulpfile.js#L87-L151

The problem was that the `masks` & `clipPath` weren't also on the defs

Everything seems to work has expected.

And so this piece of code explain why I don't want to do any processing ^^ Very custom…

**Comment by Hiswe** [comment] 2018-02-10 06:59
@jacobp100 Warn have been added in the plugin, Readme updated and  example made. 
Nothing more I can do :)

**Closed by Hiswe** 2018-02-10 06:59 UTC
